### PR TITLE
added alerts

### PR DESCRIPTION
**Pull request by tim-nguyen-cs**

### CODE REVIEW

**Comment by noll115** [comment]
The client would already know that their account is deleted/created when they are guided to another route?

**Comment by tim-nguyen-cs** [comment]
That's true, but I'd figure that additional prompts/confirmations would be helpful or reassuring (especially in updateProfile, when the page changes, but nothing actually happens)

**Comment by noll115** [comment]
I see what you mean maybe we can create a small bar in CSS at the top of each page to tell them what has happened instead of introducing more js files for one page

**Review by noll115 — CHANGES_REQUESTED** [review]
Create CSS version of alert to fit style of website

**Pull request closed without merging**
