### PR TITLE
Update to database schema

### PR DESCRIPTION
**Pull request by noll115**
`findClass()` method will now return an array of objects with each object being a tutor.
**Example Array:**
`[ { googleID: 5555, 
     name: { first: 'George', last: 'Bluementhall' } 
     rating: 2
    }
 ] `

The `classSchema` will now contain references in tutors array instead of actual predefined users which will lower the needed amount of updated required.

### CODE REVIEW

**Review by sudeepcb — APPROVED** [review]

**Review by chthota9 — COMMENTED** [review]
good

**Review by rasikakale — APPROVED** [review]
good

**Review by chthota9 — APPROVED** [review]

**Review by tim-nguyen-cs — APPROVED** [review]
refactorization looks good

**Review by jrybojad — APPROVED** [review]
V good, let's see how that will work

**Pull request merged**
